In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [7]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4), # hidden layer
    nn.Linear(4,3)  # output layer
)

deepnet = nn.Sequential(
    nn.Linear(2,2), # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3)  # output layer
)

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [29]:
# check out the parameters
for p in deepnet.named_parameters():
    print(p)
    print(' ')

('0.weight', Parameter containing:
tensor([[ 0.6098,  0.1915],
        [-0.5236, -0.3524]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.1481, -0.2868], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[ 0.5207,  0.0341],
        [-0.4758, -0.4748]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.6751, -0.5099], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.3029,  0.4805],
        [ 0.0618, -0.2559],
        [ 0.2834, -0.3626]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.0929, -0.2687,  0.3056], requires_grad=True))
 


In [28]:
# count the number of nodes 

# named_parameters() is an iterable that returns the tuple (name, numbers)

numNodesInWide = 0
for paramName, paramVect in widenet.named_parameters():
    if 'bias' in paramName:
        numNodesInWide += len(paramVect)



numNodesInDeep = 0
for paramName, paramVect in deepnet.named_parameters():
    if 'bias' in paramName:
        numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network. ' %numNodesInWide)
print('There are %s nodes in the deep network. ' %numNodesInDeep)



There are 7 nodes in the wide network. 
There are 7 nodes in the deep network. 


In [31]:
# just the parameters
for p in widenet.parameters():
    print(p)
    print(' ')

Parameter containing:
tensor([[ 0.1345, -0.3265],
        [ 0.2048, -0.3443],
        [ 0.3511,  0.5923],
        [ 0.2501,  0.1834]], requires_grad=True)
 
Parameter containing:
tensor([ 0.7050, -0.1469,  0.5201,  0.6803], requires_grad=True)
 
Parameter containing:
tensor([[-0.2829,  0.4770, -0.1283,  0.1708],
        [-0.4870,  0.0808,  0.4358,  0.4181],
        [-0.1793,  0.1474, -0.2673,  0.3838]], requires_grad=True)
 
Parameter containing:
tensor([-0.2297, -0.3833, -0.2402], requires_grad=True)
 


In [32]:
nparams = 0
for p in widenet.parameters():
    if p.requires_grad:
        print('This piece has %s parameters' %p.numel())
        nparams += p.numel()
print('\n\n Total of %s parameters ' %nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


 Total of 27 parameters 


In [33]:
# using list comprehension
nparams = np.sum([p.numel() for p in widenet.parameters() if p.requires_grad])
print('Widenet has %s parameters' %nparams)

nparams = np.sum([p.numel() for p in deepnet.parameters() if p.requires_grad])
print('Deepnet has %s parameters' %nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [39]:
# printing out model info
from torchsummary import summary 
summary(widenet,(1,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
