In [1]:
# libraries
from sklearn.model_selection import train_test_split
import numpy as np

In [8]:
## creating fake data
fakedata = np.tile(np.array([1,2,3,4]),(10,1)) + np.tile(10*np.arange(1,11),(4,1)).T
fakelabels = np.arange(10) > 4
print(fakedata),print(' ')
print(fakelabels)

[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]
 [ 41  42  43  44]
 [ 51  52  53  54]
 [ 61  62  63  64]
 [ 71  72  73  74]
 [ 81  82  83  84]
 [ 91  92  93  94]
 [101 102 103 104]]
 
[False False False False False  True  True  True  True  True]


In [10]:
# speicify the sizes of partitions
# order - train, devset, test
partitions = [.8,.1,.1]

# split the data 
train_data, testTMP, train_labels, testTMP_labels = train_test_split(fakedata, fakelabels, train_size = partitions[0])

# now split the tmp data
split = partitions[1]/np.sum(partitions[1:])
devset_data, test_data, devset_labels, test_labels = train_test_split(testTMP, testTMP_labels, train_size=split)


# sizes
print('Training data size :' + str(train_data.shape))
print('Devset data size :' + str(devset_data.shape))
print('Test data size :' + str(test_data.shape))


# print out the train/test data
print('Training data : ')
print(train_data)
print(' ')

print('Devset data : ')
print(devset_data)
print(' ')

print('test data : ')
print(test_data)
print(' ')

Training data size :(8, 4)
Devset data size :(1, 4)
Test data size :(1, 4)
Training data : 
[[101 102 103 104]
 [ 61  62  63  64]
 [ 91  92  93  94]
 [ 81  82  83  84]
 [ 51  52  53  54]
 [ 31  32  33  34]
 [ 11  12  13  14]
 [ 21  22  23  24]]
 
Devset data : 
[[71 72 73 74]]
 
test data : 
[[41 42 43 44]]
 


In [3]:
import torch
torch.cuda.is_available()

False

In [2]:
torch.__version__

'2.1.1+cu121'